### ISSUE TITLE
I/O error when trying to verify a signed wasm module

### ISSUE THREAD

**Issue by TitusVM** [wasm-signatures/wasmsign2#4]
Hi all, 

I cam accross a rather strange issue where the verification of a signed module would not work and throw "I/O error". Here are some details:

Steps to reproduce:
1. create a new rust project using `cargo new my-app`
2. compile to a wasm target: `cargo build --target=wasm32-unknown-unknown`
3. generate a new keypair using `wasmsign2 keygen -k secret.key -K public.key`
4. sign the binary: `wasmsign2 sign -i ./target/wasm32-unknown-unknown/debug/my-app.wasm -o ./my-app_signed.wasm -k secret.key`
5. verify the signed binary: `wasmsign2 verify -i ./my-app_signed.wasm -K public.key`
Result: `I/O error`

I traced the problem to this line in the [source code](https://github.com/wasm-signatures/wasmsign2/blob/07c60eee7f4c655d5a91404f5a9ffd97316d01f1/src/lib/src/wasm_module/mod.rs#L426). The instantiation of `SectionsIterator` from the reader fails and a [`WSError::IOError`](https://docs.rs/wasmsign2/latest/wasmsign2/enum.WSError.html) is produced.

Versions:
- cargo 1.83.0-nightly
- wasmsign2-cli 0.2.3
- rustup 1.27.1

Other:
- I tried both on my windows machine and a 5.15.153.1-microsoft-standard-WSL2 - both show the same behaviour.
- I tried to use ssh keys - it shows the same behaviour
- I tried various different wasm modules (also components) - same behaviour

**Comment by jedisct1** [comment]
Hi!

That seems to have been introduced by 1f49b998e65b6645da03eb9f584ed2ed05e54427 

Reverting it should fix it.
