### ISSUE TITLE
[Question] Release `0.2.5`

### ISSUE THREAD

**Issue by TitusVM** [wasm-signatures/wasmsign2#6]
Hi All! 

I was wondering whether or not you guys planned to do a release soon - I am currently building some tooling to verify wasm components and would need #5. 

All help is always appreciated!

**Comment by jedisct1** [comment]
Done!

**Comment by TitusVM** [comment]
Awesome - Thank you so much!

**Comment by TitusVM** [comment]
Thank you for releasing the [cli](https://crates.io/crates/wasmsign2-cli), any chance you could do the same with the [lib](https://crates.io/crates/wasmsign2)? 😄 Sorry for the spam...

**Comment by jedisct1** [comment]
Oops, I forgot that both had to be released independently.

Version 0.2.6 has now been released for both! Thanks!
